[feature]게임 일시정지 기능추가
P-juuny/OpenSource-C pull request #23
Opened 2024-05-13 04:21 UTC by kek705

게임 일시정지 기능을 추가합니다. p키를 입력하면 게임이 일시정지되고 다시 누르면 게임이 재개됩니다.

2024-05-16 00:24 UTC, JunYeong0314 approved these changes
고생하셨습니다!

2024-05-16 06:36 UTC, P-juuny approved these changes

2024-05-24 06:37 UTC, ParkSangsin requested changes
수고하셨습니다!
혹시 추가로 주석 깨진 부분 수정 부탁드려도 될까요??

2024-05-24 07:27 UTC, JunYeong0314 commented
> 수고하셨습니다! 혹시 추가로 주석 깨진 부분 수정 부탁드려도 될까요??

제가 주석 수정했습니다~!

2024-05-24 12:32 UTC, ParkSangsin approved these changes

2024-05-24 13:06 UTC, merged