[Fix] 한글 깨짐 현상 수정
P-juuny/OpenSource-C pull request #32
Opened 2024-05-24 16:58 UTC by ParkSangsin

## 🔥 작업 내용

> 이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)

한글로 주석 처리 시 발생하는 인코딩 문제를 각 파일 상단에 코드 한 줄을 추가함으로서 수정했습니다.

## 🏞️ 스크린샷, 영상 (선택)

> 변경된 사항을 한눈에 파악 할 수 있는 스크린샷이나 영상이 있다면 첨부해주세요

![image](https://github.com/P-juuny/OpenSource-C/assets/139088684/104ac273-4e39-4f7c-940e-46452cfcf878)

## 💁🏻‍♂️ 리뷰 요구사항(선택)

> 리뷰어가 특별히 봐주었으면 하는 부분이 있다면 작성해주세요

더 좋은 해결 방법이 있을까요??

2024-05-24 23:36 UTC, JunYeong0314 requested changes

2024-05-24 23:36 UTC, JunYeong0314 commented on SnakeAndApple.py
> +                self.begin = True
기존에 있던 p부분이 게임정지를 의미했는데 제거한 이유가 어떻게될까요 ??
그리구 print문이 주석으로 처리되어있는데 디버깅 목적으로 사용하신거라면 제거 부탁드립니다 !!

2024-05-25 06:46 UTC, ParkSangsin commented on SnakeAndApple.py
> +                self.begin = True
앗 실수로 잘못 수정된 코드네요! 바로 수정했습니다. 감사합니다!

2024-05-26 10:15 UTC, JunYeong0314 approved these changes

2024-05-27 13:23 UTC, P-juuny approved these changes

2024-05-27 14:29 UTC, merged